version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: guessr
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  guessr-app:
    image: my-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:

volumes:
  mysql-data:
