version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: guessr
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  guessr-app:
    image: my-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      BASE_URL: "http://localhost:8080"
      DROPBOX_APP_KEY: "sesasnr0u8lp4vn"
      DROPBOX_APP_SECRET: "esokjoy9jy0b8e3"
      GOOGLE_MAP_KEY: "AIzaSyAdL2kb4X21i9njeKk-dFQE_FN7jvacQeE"
      JDBC_DATABASE_PASSWORD: "userpassword123"
      JDBC_DATABASE_URL: "jdbc:mysql://mysql-db:3306/guessr?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
      JDBC_DATABASE_USERNAME: "user"

volumes:
  mysql-data:
